### ISSUE TITLE
Would `application/json-seq` be a suitable mime type for `jsonl`?

### ISSUE THREAD

**Issue by AndreCAndersen** [wardi/jsonlines#36] opened 2020-01-27 20:52 UTC
I came accross this RFC: https://tools.ietf.org/html/rfc7464

It suggests using `application/json-seq` as the mimetype for json objects delimited by new lines. It is also cited on [wikipedia](https://en.wikipedia.org/wiki/JSON_streaming) . For completeness sake, I also created a stackoverflow question/answer [here](https://stackoverflow.com/q/59938644/604048) .

If this is the correct mime type for `jsonl`, then I suggest adding it to jsonlines.org since it was the first hit on google, when researching this.

**Comment by wardi** [comment] 2020-01-27 20:59
sounds good to me, mind making the change?

**Comment by AndreCAndersen** [comment] 2020-02-14 09:31
@wardi Unfortunately I discovered it is likely not the "correct" mime-type. [I asked over at SO](https://stackoverflow.com/a/59998781/604048), and was made aware that `json-seq` includes a [<RS>](https://www.compart.com/en/unicode/U+001E) character. While `jsonl`, from what I understand, relies on just line separators. Some suggestions which showed up where:

    application/json-lines
    application/jsonl
    applicaiton/x-...

I suggest we somehow figure out which is used most, and support it as preferred (as well as listing other alternatives).

To start:

Google returns 9 results for `"application/json-lines"` and 52 for `"application/jsonl"`. Just for reference `"application/json-seq"` gets 1340 results.

**Comment by glensc** [comment] 2021-03-03 15:39
There's also: `application/json-l` and extension `.jsonl`:
- https://github.com/ndjson/ndjson-spec/issues/23

**Comment by sp4ce** [comment] 2022-12-19 18:51
I suggest closing this issue and keeping only https://github.com/wardi/jsonlines/issues/19 open to avoid confusion `application/json-seq` does not work (because jsonl is not the same), so we would probably need another type. I suggest closing this issue because the title of the issue is about json-seq and nothing else.

**Closed** 2023-04-03 16:54 UTC
